basic.forever(() => {
    console.log("test start")
    basic.pause(1000)
    lights.lights1.setBrightness(100)
    basic.pause(1000)
    lights.lights1.setBrightness(75)
    basic.pause(1000)
    lights.lights1.setBrightness(50)
    basic.pause(1000)
    lights.lights1.setBrightness(25)
    basic.pause(1000)
    lights.lights1.setBrightness(10)
    basic.pause(1000)
    lights.lights1.setBrightness(0)
    console.log("test end")
})
